
CREATE DATABASE "CRM_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "CRM_DB" OWNER TO "CRM_USER";

CREATE DATABASE "BILLING_DB" WITH TEMPLATE = template0 ENCODING = 'UTF8' CONNECTION LIMIT = -1;
ALTER DATABASE "BILLING_DB" OWNER TO "BILLING_USER";